#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <mios/io.h>
#include <mios/task.h>
#include <mios/block.h>
#include <mios/cli.h>
#include "stm32n6_flash.h"

#include "stm32n6_clk.h"
#include "stm32n6_pwr.h"
#include "stm32n6_usb.h"
#include "stm32n6_eth.h"
#include "stm32n6_uart.h"
#include "stm32n6_adc.h"

#include <usb/usb.h>

#define BLINK_GPIO GPIO_PG(10) // Red LED (LD2)

static void __attribute__((constructor(101)))
board_init_clk(void)
{
  stm32n6_init_pll(48000000);

  stm32n6_pwr_vddio3_enable(STM32N6_VDDIO_1V8);
  stm32n6_pwr_usb33_enable();
}

static void __attribute__((constructor(102)))
board_init_console(void)
{
  static stm32_uart_stream_t console;
  stdio = stm32n6_uart_init(&console, 1, 115200, GPIO_PE(5), GPIO_PE(6),
                            UART_CTRLD_IS_PANIC, "console");
}

__attribute__((noreturn))
static void *
blinker(void *arg)
{
  gpio_conf_output(BLINK_GPIO, GPIO_PUSH_PULL, GPIO_SPEED_LOW,
                   GPIO_PULL_NONE);
  while(1) {
    gpio_set_output(BLINK_GPIO, 1);
    usleep(500000);
    gpio_set_output(BLINK_GPIO, 0);
    usleep(500000);
  }
}

static void __attribute__((constructor(800)))
board_init_late(void)
{
  thread_create(blinker, NULL, 512, "blinker", 0, 0);

  struct usb_interface_queue q;
  STAILQ_INIT(&q);

  usb_cdc_create_shell(&q);

  stm32n6_otghs_create(0x6666, 0x0500, "Lonelycoder", "stm32n6-dk", &q);

  stm32n6_eth_init(GPIO_UNUSED, GPIO_PD(12), GPIO_PD(1),
                   1, ETHPHY_MODE_RGMII);
}

// Embedded FSBL image generated by STM32_SigningTool_CLI
#include "fsbl_image.h"

static error_t
write_fsbl_to_partition(cli_t *cli, int partition, const char *name)
{
  block_iface_t *bi = stm32n6_flash_get_partition(partition);
  if(bi == NULL) {
    cli_printf(cli, "%s: partition not available\n", name);
    return ERR_OPERATION_FAILED;
  }

  const size_t len = build_stm32n6_dk_fsbl_bin_len;
  size_t blocks_needed = (len + bi->block_size - 1) / bi->block_size;

  cli_printf(cli, "%s: %d bytes\n", name, (int)len);

  error_t err = block_erase(bi, 0, blocks_needed);
  if(err) { cli_printf(cli, "  Erase failed: %d\n", err); return err; }

  err = block_write(bi, 0, 0, build_stm32n6_dk_fsbl_bin, len);
  if(err) { cli_printf(cli, "  Write failed: %d\n", err); return err; }

  cli_printf(cli, "  OK\n");
  return 0;
}

static error_t
cmd_install_bootloader(cli_t *cli, int argc, char **argv)
{
  error_t err;

  err = write_fsbl_to_partition(cli, FLASH_PARTITION_FSBL1, "FSBL1");
  if(err) return err;

  err = write_fsbl_to_partition(cli, FLASH_PARTITION_FSBL2, "FSBL2");
  if(err) return err;

  cli_printf(cli, "Done. Power cycle to boot from flash.\n");
  return 0;
}

CLI_CMD_DEF("install-bootloader", cmd_install_bootloader);

// ---------------------------------------------------------------
// ADC bring-up + diag — VREFINT only for now (channel 17 of ADC1,
// internally driven, no GPIO involved). Use this to validate the
// stm32n6_adc driver end-to-end before adding any external pins.
// ---------------------------------------------------------------

static void __attribute__((constructor(900)))
board_init_adc(void)
{
  // PCSEL bit isn't strictly required for internal channels per
  // RM0486 §32.4.12 but we set it anyway so the same path works
  // if external channels get added later.
  stm32n6_adc_init(ADC1_BASE, 1u << 17, 0);

  // Enable VREFINT analog source. Per RM Table 242, ADC1 VINP[17]
  // is the VREFINT channel; CCR bit 22 (VREFEN) gates it on.
  reg_set_bit(ADC12_CCR, 22);

  // Slow sample time for VREFINT — datasheet typical T_S_TEMP/VREFINT
  // is in the µs range, so use SMP=7 (255.5 cycles ≈ 5 µs at 50 MHz
  // ADC clock) to be safe.
  stm32n6_adc_set_smpr(ADC1_BASE, 17, 7);
}

static error_t
cmd_adc(cli_t *cli, int argc, char **argv)
{
  cli_printf(cli, "ADC1 registers:\n");
  cli_printf(cli, "  CR=0x%08x  ISR=0x%08x  CFGR1=0x%08x\n",
             reg_rd(ADC1_BASE + ADCx_CR),
             reg_rd(ADC1_BASE + ADCx_ISR),
             reg_rd(ADC1_BASE + ADCx_CFGR1));
  cli_printf(cli, "  PCSEL=0x%08x  DIFSEL=0x%08x  CALFACT=0x%08x\n",
             reg_rd(ADC1_BASE + ADCx_PCSEL),
             reg_rd(ADC1_BASE + ADCx_DIFSEL),
             reg_rd(ADC1_BASE + ADCx_CALFACT));
  cli_printf(cli, "  ADC12_CCR=0x%08x  VREFBUF_CSR=0x%08x\n",
             reg_rd(ADC12_CCR),
             reg_rd(0x56003C00));

  // Sample VREFINT a few times via the blocking single-channel path.
  // Expected: ~1500 raw with VREF+ = 3.3 V (VREFINT typ. 1.21 V).
  // If we get something close to that, the whole driver chain works:
  // VREFBUF clock enabled, VREFBUF in external mode (HIZ=1), ADC
  // calibrated, channel mux switching.
  cli_printf(cli, "VREFINT (ch17):\n");
  for(int i = 0; i < 4; i++) {
    int raw = stm32n6_adc_read_channel(ADC1_BASE, 17);
    cli_printf(cli, "  raw=%4d  (~%d mV at VREF=3.3V/12-bit)\n",
               raw, raw * 3300 / 4095);
  }
  return 0;
}

CLI_CMD_DEF("adc", cmd_adc);
