#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <mios/io.h>
#include <mios/task.h>
#include <mios/block.h>
#include <mios/fs.h>
#include <mios/cli.h>

#include "stm32n6_clk.h"
#include "stm32n6_pwr.h"
#include "stm32n6_usb.h"
#include "stm32n6_eth.h"
#include "stm32n6_uart.h"

#include <usb/usb.h>

#define BLINK_GPIO GPIO_PG(10) // Red LED (LD2)

static void __attribute__((constructor(101)))
board_init_clk(void)
{
  stm32n6_init_pll(48000000);

  stm32n6_pwr_vddio3_enable(STM32N6_VDDIO_1V8);
  stm32n6_pwr_usb33_enable();
}

static void __attribute__((constructor(102)))
board_init_console(void)
{
  static stm32_uart_stream_t console;
  stdio = stm32n6_uart_init(&console, 1, 115200, GPIO_PE(5), GPIO_PE(6),
                            UART_CTRLD_IS_PANIC, "console");
}

__attribute__((noreturn))
static void *
blinker(void *arg)
{
  gpio_conf_output(BLINK_GPIO, GPIO_PUSH_PULL, GPIO_SPEED_LOW,
                   GPIO_PULL_NONE);
  while(1) {
    gpio_set_output(BLINK_GPIO, 1);
    usleep(500000);
    gpio_set_output(BLINK_GPIO, 0);
    usleep(500000);
  }
}

static void __attribute__((constructor(800)))
board_init_late(void)
{
  thread_create(blinker, NULL, 512, "blinker", 0, 0);

  struct usb_interface_queue q;
  STAILQ_INIT(&q);

  usb_cdc_create_shell(&q);

  stm32n6_otghs_create(0x6666, 0x0500, "Lonelycoder", "stm32n6-dk", &q);

  stm32n6_eth_init(GPIO_UNUSED, GPIO_PD(12), GPIO_PD(1),
                   1, ETHPHY_MODE_RGMII);
}

block_iface_t *xspi_norflash_create(void);

static error_t
cmd_fs(cli_t *cli, int argc, char **argv)
{
  block_iface_t *bi = xspi_norflash_create();
  if(bi == NULL)
    return ERR_OPERATION_FAILED;
  fs_init(bi);
  return 0;
}

CLI_CMD_DEF("fs", cmd_fs);


// Embedded FSBL image generated by STM32_SigningTool_CLI
#include "fsbl_image.h"

static error_t
write_fsbl_to_flash(cli_t *cli, block_iface_t *bi, size_t flash_block,
                    const char *name)
{
  const size_t len = build_stm32n6_dk_fsbl_bin_len;
  size_t blocks_needed = (len + bi->block_size - 1) / bi->block_size;

  cli_printf(cli, "%s: %d bytes at block %d\n", name, (int)len, (int)flash_block);

  error_t err = block_erase(bi, flash_block, blocks_needed);
  if(err) { cli_printf(cli, "  Erase failed: %d\n", err); return err; }

  err = block_write(bi, flash_block, 0, build_stm32n6_dk_fsbl_bin, len);
  if(err) { cli_printf(cli, "  Write failed: %d\n", err); return err; }

  cli_printf(cli, "  OK\n");
  return 0;
}

static error_t
cmd_install_bootloader(cli_t *cli, int argc, char **argv)
{
  block_iface_t *bi = xspi_norflash_create();
  if(bi == NULL)
    return ERR_OPERATION_FAILED;

  error_t err;

  // Write FSBL1 at flash 0x0
  err = write_fsbl_to_flash(cli, bi, 0, "FSBL1");
  if(err) return err;

  // Write FSBL2 at flash 0x40000
  size_t fsbl2_block = 0x40000 / bi->block_size;
  err = write_fsbl_to_flash(cli, bi, fsbl2_block, "FSBL2");
  if(err) return err;

  cli_printf(cli, "Done. Power cycle to boot from flash.\n");
  return 0;
}

CLI_CMD_DEF("install-bootloader", cmd_install_bootloader);
