name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: sudo apt update && sudo apt install  --no-install-recommends --no-install-suggests gcc-arm-none-eabi
    - name: make
      run: make -j`nproc` allplatforms
